/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "GPIO.h"
#include "STM32F103C6.h"

void RCC_Init()
{
	//PORTA RCC CLOCK ENABLE:
	RCC_PORTA_CLK_EN();
	//PORTB RCC CLOCK ENABLE:
	RCC_PORTB_CLK_EN();
}

void GPIO_Init()
{
	GPIO_PinConfig_t PIN_Conf;
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_1;
	PIN_Conf.GPIO_MODE = GPIO_MODE_FLOATING_INPUT;
	MCAL_GPIO_Init(PORTA, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_13;
	PIN_Conf.GPIO_MODE = GPIO_MODE_FLOATING_INPUT;
	MCAL_GPIO_Init(PORTA, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_1;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(PORTB, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_13;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(PORTB, &PIN_Conf);
}

void delay(int x)
{
	int i,j;
	for(i=0;i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}

int main(void)
{
	RCC_Init();
	GPIO_Init();
    /* Loop forever */
	while(1)
	{
		if(MCAL_GPIO_ReadPin(PORTA, GPIO_PIN_1)==0)
		{
			MCAL_GPIO_TogglePin(PORTB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(PORTA, GPIO_PIN_1)==0);
		}
		if(MCAL_GPIO_ReadPin(PORTA, GPIO_PIN_13)==1)
		{
			MCAL_GPIO_TogglePin(PORTB, GPIO_PIN_13);
		}
		delay(255);
	}
}
