/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>

//register addresses:
#define RCC_BASE 0x40021000
#define PORTA_BASE 0x40010800
#define RCC_APB2ENR *((volatile uint32_t*)(RCC_BASE+0X18))
#define PORTA_CRH   *((volatile uint32_t*)(PORTA_BASE+0X04))
#define PORTA_ODR   *((volatile uint32_t*)(PORTA_BASE+0X0C))

uint8_t G_Variables[3]={1,2,3};
uint8_t const C_Variables[3]={1,2,3};
uint8_t BSS_Variables[3];

int main(void)
{
	volatile int i;
	RCC_APB2ENR |= (1<<2);
	PORTA_CRH &= 0Xff0fffff;
	PORTA_CRH |= 0X00200000;
	while(1)
	{
		PORTA_ODR |= (1<<13);
		for(i=0;i<5000;i++);
		PORTA_ODR &= ~(1<<13);
		for(i=0;i<5000;i++);
	}
	return 0;
}
