/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define MCU_MASTER
#define MCU_SLAVE


#include "GPIO.h"
#include "STM32F103C6.h"
#include "LCD.h"
#include "KEYPAD.h"
#include "Seven_segment.h"
#include "EXTI.h"
#include "USART.h"
#include "SPI.h"

void CLOCK_INIT()
{
	//RCC ENABLE:
	RCC_PORTA_CLK_EN();
	RCC_PORTB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

uint16_t data;

void SPI_IRQ_CALLBACK(struct SPI_IRQ_SRC IRQ_SRC)
{
#ifdef MCU_SLAVE
	if(IRQ_SRC.RXNE)
	{
		data = 0xF;
		MCAL_SPI_SEND_RECEIVE_DATA(SPI1, &data, POLLING_DISABLE);
		MCAL_UART_TRANSMIT(USART1, &data, POLLING_ENABLE);
	}
#endif
}

void UART_IRQ_CALLBACK(void)
{
#ifdef MCU_MASTER
	MCAL_UART_RECEIVE(USART1, &data, POLLING_DISABLE);
	MCAL_UART_TRANSMIT(USART1, &data, POLLING_ENABLE);
	//Send to SPI:
	MCAL_GPIO_WritePin(PORTA, GPIO_PIN_4, 0);
	MCAL_SPI_SEND_RECEIVE_DATA(SPI1, &data, POLLING_ENABLE);
	MCAL_GPIO_WritePin(PORTA, GPIO_PIN_4, 1);
#endif
}

int main(void)
{
	CLOCK_INIT();

	USART_Config_t UART_Config;
	UART_Config.UART_IRQ = UART_IRQ_RXNE;
	UART_Config.PF_IRQ_CallBack = UART_IRQ_CALLBACK;
	UART_Config.BAUD_RATE = BAUD_RATE_115200;
	UART_Config.DATA_BITS = DATA_BITS_Eight;
	UART_Config.PARITY_BITS = PARITY_BITS_Disabled;
	UART_Config.FLOW_CONTROL = FLOW_CONTROL_DISABLE;
	UART_Config.STOP_BITS = STOP_BITS_ONE;
	UART_Config.USART_MODE = USART_MODE_TX_RX;

	MCAL_UART_Init(USART1,&UART_Config);
	MCAL_UART_GPIO_SET_PINS(USART1);

	SPI_Config_t SPI_Config;
	SPI_Config.CLOCK_PHASE = CLOCK_PHASE_SECOND;
	SPI_Config.CLOCK_POLARITY = CLOCK_POLARITY_IDLE_1;
	SPI_Config.DATA_SIZE = DATA_SIZE_8_BIT;
	SPI_Config.FRAME_FORMAT = FRAME_FORMAT_MSB;
	SPI_Config.SPI_BAUD_RATE = SPI_BAUD_RATE_8;
	SPI_Config.COMMUNICATION_MODE = COMMUNICATION_MODE_2_LINES;

	GPIO_PinConfig_t PIN_Config;

#ifdef MCU_MASTER
	SPI_Config.DEVICE_MODE = DEVICE_MODE_MASTER;
	SPI_Config.SPI_IRQ = SPI_IRQ_DISABLE;
	SPI_Config.NSS = NSS_SOFTWARE_SET;
	SPI_Config.P_IRQ_Callback = NULL;

	PIN_Config.GPIO_PIN_NUMBER = GPIO_PIN_4;
	PIN_Config.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Config.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(PORTA, &PIN_Config);

	MCAL_GPIO_WritePin(PORTA, GPIO_PIN_4, 1);
#endif

#ifdef MCU_SLAVE
	SPI_Config.DEVICE_MODE = DEVICE_MODE_SLAVE;
	SPI_Config.SPI_IRQ = SPI_IRQ_RXNEIE_ENABLE;
	SPI_Config.NSS = NSS_HARDWARE_SLAVE;
	SPI_Config.P_IRQ_Callback = SPI_IRQ_CALLBACK;

#endif

	MCAL_SPI_INIT(SPI1, &SPI_Config);
	MCAL_SPI_GPIO_SET_PINS(SPI1);


	/* Loop forever */
	while(1)
	{

	}
}
