/*
 * Seven_segment.c
 *
 *  Created on: 24 Jul 2024
 *      Author: Mahmoud
 */


#include "Seven_segment.h"

void SEVEN_SEGMENT_Init()
{
	GPIO_PinConfig_t PIN_Conf;
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_9;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(SEVEN_SEGMENT_PORT, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_10;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(SEVEN_SEGMENT_PORT, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_11;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(SEVEN_SEGMENT_PORT, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_12;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(SEVEN_SEGMENT_PORT, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_13;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(SEVEN_SEGMENT_PORT, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_14;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(SEVEN_SEGMENT_PORT, &PIN_Conf);

	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_15;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(SEVEN_SEGMENT_PORT, &PIN_Conf);
}

void SEVEN_SEGMENT_DISPLAY(uint8_t VAL)
{
	MCAL_GPIO_WritePort(SEVEN_SEGMENT_PORT, VAL<<9);
}
