/*
 * LCD.c
 *
 * Created: 15/07/2024 11:36:12 AM
 *  Author: Mahmoud
 */ 


#include "LCD.h"

static int cursor_pos = 0;

void delay(int x)
{
	int i,j;
	for(i=0;i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}


void LCD_INIT()
{
	delay(35);
	//SET_BIT(CTRL_DIR_LCD,RS_SWITCH);
	GPIO_PinConfig_t PIN_Conf;
	PIN_Conf.GPIO_PIN_NUMBER = RS_SWITCH;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_CTRL, &PIN_Conf);
	//SET_BIT(CTRL_DIR_LCD,RW_SWITCH);
	PIN_Conf.GPIO_PIN_NUMBER = RW_SWITCH;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_CTRL, &PIN_Conf);
	//SET_BIT(CTRL_DIR_LCD,EN_SWITCH);
	PIN_Conf.GPIO_PIN_NUMBER = EN_SWITCH;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_CTRL, &PIN_Conf);

	delay(35);

	//SET BIT 0 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_0;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);
	//SET BIT 1 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_1;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);
	//SET BIT 2 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_2;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);
	//SET BIT 3 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_3;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);
	//SET BIT 4 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_4;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);
	//SET BIT 5 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_5;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);
	//SET BIT 6 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_6;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);
	//SET BIT 7 TO OUTPUT
	PIN_Conf.GPIO_PIN_NUMBER = GPIO_PIN_7;
	PIN_Conf.GPIO_MODE = GPIO_MODE_OUT_PUSH_PULL;
	PIN_Conf.GPIO_OUTPUT_FREQ = GPIO_OUTPUT_FREQ_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &PIN_Conf);

	MCAL_GPIO_WritePin(LCD_CTRL, RS_SWITCH,0);
	MCAL_GPIO_WritePin(LCD_CTRL, RW_SWITCH,0);
	MCAL_GPIO_WritePin(LCD_CTRL, EN_SWITCH,0);

	LCD_CLEAR();
	#ifdef EIGHT_BIT_MODE
		LCD_WRITE_COMMAND(LCD_FUNCTION_8BIT_2LINES);
	#endif
	
	/*#ifdef FOUR_BIT_MODE
		LCD_WRITE_COMMAND(0x02);
		LCD_WRITE_COMMAND(LCD_FUNCTION_4BIT_2LINES);
	#endif*/
	
	LCD_WRITE_COMMAND(LCD_ENTRY_MODE);
	LCD_WRITE_COMMAND(LCD_BEGIN_AT_FIRST_ROW);
	LCD_WRITE_COMMAND(LCD_DISP_ON_CURSOR);
}

void LCD_WRITE_COMMAND(unsigned char command)
{
	#ifdef EIGHT_BIT_MODE
		MCAL_GPIO_WritePort(LCD_PORT, command);
		MCAL_GPIO_WritePin(LCD_CTRL,RS_SWITCH,0);
		MCAL_GPIO_WritePin(LCD_CTRL,RW_SWITCH,0);
		LCD_KICK();
	#endif
	
	/*#ifdef FOUR_BIT_MODE
	LCD_PORT = (LCD_PORT & 0xF0F) | (command & 0xF0);
	CLEAR_BIT(LCD_CTRL->ODR,RW_SWITCH);
	CLEAR_BIT(LCD_CTRL->ODR,RS_SWITCH);
	LCD_KICK();
	LCD_PORT = (LCD_PORT & 0xF0F) | (command << 4);
	CLEAR_BIT(LCD_CTRL->ODR,RW_SWITCH);
	CLEAR_BIT(LCD_CTRL->ODR,RS_SWITCH);
	LCD_KICK();
	#endif*/
}

void LCD_WRITE_CHAR(unsigned char character)
{
	if(cursor_pos==16)
	{
		LCD_MOVE_CURSOR(2,0);
	}
	if(cursor_pos==32)
	{
		LCD_WRITE_COMMAND(LCD_CLEAR_SCREEN);
		LCD_MOVE_CURSOR(1,0);
		cursor_pos=0;
	}
	cursor_pos++;
	
	#ifdef EIGHT_BIT_MODE
		MCAL_GPIO_WritePin(LCD_CTRL,RS_SWITCH,1);
		MCAL_GPIO_WritePort(LCD_PORT, character);
		MCAL_GPIO_WritePin(LCD_CTRL,RS_SWITCH,1);
		MCAL_GPIO_WritePin(LCD_CTRL,RW_SWITCH,0);
		LCD_KICK();
	#endif
	
	/*#ifdef FOUR_BIT_MODE
		LCD_PORT = (LCD_PORT & 0xF0F) | (character & 0xF0);
		SET_BIT(LCD_CTRL->ODR,RS_SWITCH);
		CLEAR_BIT(LCD_CTRL->ODR,RW_SWITCH);
		LCD_KICK();
		LCD_PORT = (LCD_PORT & 0xF0F) | (character << 4);
		SET_BIT(LCD_CTRL->ODR,RS_SWITCH);
		CLEAR_BIT(LCD_CTRL->ODR,RW_SWITCH);
		LCD_KICK();
	#endif*/
}


void LCD_WRITE_STRING(const char *str)
{
	while(*str!='\0')
	{
		LCD_WRITE_CHAR(*str++);
	}
}

/*void LCD_CHECK_BUSY()
{
	#ifdef EIGHT_BIT_MODE
	//DATA_DIR_LCD = 0x00;
	#endif
	
	#ifdef FOUR_BIT_MODE
	//DATA_DIR_LCD = 0x0F;
	#endif
	
	//SET_BIT(LCD_CTRL,RW_SWITCH);
	//CLEAR_BIT(LCD_CTRL,RS_SWITCH);
	LCD_KICK();
	//DATA_DIR_LCD = 0xFF;
	//CLEAR_BIT(LCD_CTRL,RW_SWITCH);
}*/

void LCD_KICK()
{
	MCAL_GPIO_WritePin(LCD_CTRL,EN_SWITCH,1);
	delay(5);
	MCAL_GPIO_WritePin(LCD_CTRL,EN_SWITCH,0);
}

void LCD_CLEAR()
{
	LCD_WRITE_COMMAND(LCD_CLEAR_SCREEN);
	cursor_pos = 0;
	LCD_MOVE_CURSOR(1,0);
}

void LCD_MOVE_CURSOR(unsigned char line, unsigned char position)
{
	if (line == 1)
	{
		if (position < 16 && position >= 0)
		{
			LCD_WRITE_COMMAND(LCD_BEGIN_AT_FIRST_ROW+position);
			cursor_pos = position;
		}
	}
	if (line == 2)
	{
		if (position < 16 && position >= 0)
		{
			LCD_WRITE_COMMAND(LCD_BEGIN_AT_SECOND_ROW+position);
			cursor_pos = position+16;
		}
	}
}


void LCD_CUSTOM_CHAR(void)
{
	LCD_WRITE_COMMAND(64);
	LCD_WRITE_CHAR(0);
	LCD_WRITE_CHAR(14);
	LCD_WRITE_CHAR(17);
	LCD_WRITE_CHAR(2);
	LCD_WRITE_CHAR(4);
	LCD_WRITE_CHAR(4);
	LCD_WRITE_CHAR(0);
	LCD_WRITE_CHAR(4);
	LCD_WRITE_COMMAND(LCD_BEGIN_AT_FIRST_ROW);
	LCD_WRITE_CHAR(0);
}
