/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//REGISTER ADDRESSES:
//RCC REGISTERS:
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *((volatile unsigned int*)(RCC_BASE+0x18))

//GPIO REGISTERS:
//PORT A REGISTERS:
#define PORTA_BASE 0x40010800
#define PORTA_CRL *((volatile unsigned int*)(PORTA_BASE+0x00))
#define PORTA_CRH *((volatile unsigned int*)(PORTA_BASE+0x04))
#define PORTA_IDR *((volatile unsigned int*)(PORTA_BASE+0x08))

//PORT B REGISTERS:
#define PORTB_BASE 0x40010C00
#define PORTB_CRL *((volatile unsigned int*)(PORTB_BASE+0x00))
#define PORTB_CRH *((volatile unsigned int*)(PORTB_BASE+0x04))
#define PORTB_ODR *((volatile unsigned int*)(PORTB_BASE+0x0C))


void RCC_init()
{
	//ENABLE CLOCK FOR PORT A
	RCC_APB2ENR |= (1<<2);
	//ENABLE CLOCK FOR PORT B
	RCC_APB2ENR |= (1<<3);
}

void GPIO_init()
{
	//PORT A PIN 1 FLOATING INPUT SETUP:
	PORTA_CRL &= 0xFFFFFF0F;
	PORTA_CRL |= 0x40;
	//PORT A PIN 13 FLOATING INPUT SETUP:
	PORTA_CRH &= 0xFF0FFFFF;
	PORTA_CRH |= 0x00400000;
	//PORT B PIN 1 GENERAL PURPOSE OUTPUT PUSH-PULL:
	PORTB_CRL &= 0xFFFFFF0F;
	PORTB_CRL |= 0x20;
	//PORT B PIN 13 GENERAL PURPOSE OUTPUT PUSH-PULL:
	PORTB_CRH &= 0xFF0FFFFF;
	PORTB_CRH |= 0x00200000;
	//TURN OFF LED 1 AND LED 13 AT RESET:
	//PORTB_ODR |= (1<<1);
	//PORTB_ODR |= (1<<13);
}

void delay(int x)
{
	int i,j;
	for(i=0;i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}

int main(void)
{
	RCC_init();
	GPIO_init();
    /* Loop forever */
	while(1)
	{
		if((PORTA_IDR&(1<<1))==0)
		{
			PORTB_ODR ^= (1<<1);
			while((PORTA_IDR&(1<<1))==0);
		}
		if(((PORTA_IDR & (1<<13)) >> 13) == 1)
		{
			PORTB_ODR ^= (1<<13);
		}
		delay(255);
	}
}
