/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//register addresses:
//RCC registers:
#define RCC_BASE 0x40021000
#define RCC_APB2ENR  *((volatile unsigned int*)(RCC_BASE+0X18))

//PORTA registers:
#define PORTA_BASE 0x40010800
#define PORTA_CRL    *((volatile unsigned int*)(PORTA_BASE+0X00))
#define PORTA_CRH    *((volatile unsigned int*)(PORTA_BASE+0X04))
#define PORTA_ODR    *((volatile unsigned int*)(PORTA_BASE+0X0C))

//EXTI registers:
#define EXTI_BASE 0x40010400
#define EXTI_IMR     *((volatile unsigned int*)(EXTI_BASE+0x00))
#define EXTI_RTSR    *((volatile unsigned int*)(EXTI_BASE+0x08))
#define EXTI_PR      *((volatile unsigned int*)(EXTI_BASE+0x14))

//AFIO registers:
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *((volatile unsigned int*)(AFIO_BASE+0x08))

//NVIC registers:
#define NVIC_BASE 0xE000E100
#define NVIC_ISER *((volatile unsigned int*)(NVIC_BASE+0x00	))

void RCC_init()
{
	RCC_APB2ENR |= (1<<2); //PORT_A CLOCK EN
	RCC_APB2ENR |= (1<<0); //AFIO CLOCK EN
}
void GPIOA_init()
{
	PORTA_CRH &= 0Xff0fffff; //config PORTA.13
	PORTA_CRH |= 0X00200000; //config PORTA.13 output
	PORTA_CRL |= 0x0100;	 //config PORTA.0 floating input
}
void EXTI_init()
{
	EXTI_IMR |= (1<<0);   //Masking line 0
	EXTI_RTSR |= (1<<0);  //Rising edge for line 0
	AFIO_EXTICR1 = 0;     //EXTI 0 config for POTRA
	NVIC_ISER |= (1<<6);  //ENABLE NVIC IRQ6
}
void EXTI0_IRQHandler(void)
{
	PORTA_ODR ^= (1<<13); //Toggle PORTA.13
	EXTI_PR |= (1<<0);    //Clear interrupt request for line 0
}
int main(void)
{
	RCC_init();
	GPIOA_init();
	EXTI_init();

	while(1)
	{
	}
	return 0;
}
